format = """
[┌](bold green) \
$username$directory\
$git_branch$git_status$git_commit$git_metrics\
$cmake$rust$python
[└](bold green) $time$status$cmd_duration$character
"""

[status]
disabled = false

[time]
disabled = false
format = "[$time]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "


[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[cmd_duration]
format = "[羽$duration]($style)"

[rust]
format = "[$symbol($version )]($style)"
symbol = " "
