theme = "material_oceanic"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "¦"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
