[language-server.rust-analyzer.config]
# check.command = "check"
check.command = "clippy"
cargo.buildScripts.enable = true
procMacro.enable = true 

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "glsl"
file-types = ["rgen", "rchit", "rmiss", "glsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-vscode-14"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }


[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "markdown"
language-servers = ["codebook"]
