[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.buildScripts.enable = true
procMacro.enable = true 

[[language]]
name = "glsl"
file-types = ["rgen", "rchit", "rmiss", "glsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
